apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-standalone
  labels:
    heritage: helm
spec:
  replicas: 1
  selector:
    name: redis-standalone
    mode: standalone
    provider: redis
  template:
    metadata:
      labels:
        name: redis-standalone
        mode: standalone
        provider: redis
        app: redis-standalone
    spec:
      containers:
      - name: redis-standalone
        image: kubernetes/redis:v1
        env:
        - name: MASTER
          value: "true"
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
      volumes:
        - name: data
          emptyDir: {}
---

apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    provider: redis
    heritage: helm
spec:
  ports:
  - port: 6379
  selector:
    provider: redis
